#!/usr/bin/expect

##
##    The Oracle Storage HCL Testkit is a suite of tests for certifying
##    storage with Oracle VM (OVM).
##    Copyright (C) 2013 Oracle USA, Inc 
##
##    This file is part of the Oracle Storage HCL Testkit.
##
##    The Oracle Storage HCL Testkit is free software; you can redistribute 
##    it and/or modify it under the terms of the GNU General Public License 
##    as published by the Free Software Foundation; either version 2 of the 
##    License, or (at your option) any later version.
##
##    The Oracle Storage HCL Testkit is distributed in the hope that it will
##    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
##    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with the Oracle Storage HCL Testkit.  If not; write to the 
##    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
##    Boston, MA 02110-1301 USA. Or see <http://www.gnu.org/licenses/>.
##

source commonExpectDef.cli

################ global variables #####################
set prompt "OVM> "
set VERBOSE [lindex $argv 2]
set send_human {.1 .3 1 .05 2}

set successMsg "Status: Success"
set failureMsg "Status: Failure"
set timeout 900

set myRepo ""
set myPoolFS ""
set repoDiskName ""
set poolfsDiskName ""
set sharedSpare ""
set spareDiskName ""

########## externally defined variables ############
set ovmUser ${ovmUser}
set adminServer ${adminServer}
set ovmPassword [lindex $argv 0]
set ovmAgentUsername ${ovmAgentUsername}
set ovmAgentPassword [lindex $argv 1]
set ovmServerMasterIP ${ovmServerMasterIP}
set ovmServerSlaveIP ${ovmServerSlaveIP}


## Pool Parameters
set serverPoolName fc_testpool1
set serverPoolIP ${serverPoolIP}

## Repository Parameters
set repoName repo_fc1.1
set vdiskName vdisk_fc1.1

## VM Parameters
set vmName VM_fc1.1

## Network
set VM_Network ${VM_Network}
set VM_Netmask ${VM_Netmask}
set VM_NetworkPort ${VM_NetworkPort}
set ovmServerMaster_vmnetworkIP ${ovmServerMaster_vmnetworkIP} 
set ovmServerSlave_vmnetworkIP ${ovmServerSlave_vmnetworkIP} 
set vNIC 00:21:f6:ca:fe:ba
set vNIC1 00:21:f6:ca:fe:b2
set vNIC2 00:21:f6:ca:fe:b1

## Storage
set SAN_ServerName "Unmanaged FibreChannel Storage Array"
set storageNetworkPort "generic"


## Logging
set hcllogdir ${hcllogdir}
set logfile $hcllogdir
append logfile "FibreChannel_TestSuite1-Resize.log"
set testStep 0

#################################################################
##
##       Test Suite 1: Fibre Channel with Generic Plugin
##
#################################################################
##
##      +-----+-------+-------+---------------+---------------+
##      | LUN |  Old  |  New  | OVM Server #1 | OVM Server #2 |
##      +-----+-------+-------+---------------+---------------+
##      |  1  |  5 GB |  7 GB |       X       |               |
##      |  2  | 10 GB | 12 GB |               |       X       |
##      +-----+-------+-------+---------------+---------------+
##

log_user 0
OVMlogin
log_file -a $logfile

send_user "\nReading server info...\n"
set slist [getServerIDs]
array set myServerInfo [verifyServers $ovmServerMasterIP $ovmServerSlaveIP $storageNetworkPort $VM_NetworkPort $slist]

if {[info exists myServerInfo($ovmServerMasterIP,name)]} {
    set masterName $myServerInfo($ovmServerMasterIP,name)
} else {
    send_user "The server $ovmServerMasterIP cannot be found!\n"
    send_user "Exiting...\n"
    finishRun 4
}
if {[info exists myServerInfo($ovmServerSlaveIP,name)]} {
    set secondaryName $myServerInfo($ovmServerSlaveIP,name)
} else {
    send_user "The server $ovmServerSlaveIP cannot be found!\n"
    send_user "Exiting...\n"
    finishRun 4
}

set masterID $myServerInfo($ovmServerMasterIP,id)
set secondaryID $myServerInfo($ovmServerSlaveIP,id)

send_user "\n---------------------------------------------------------------------------------\n"
send_user "GSFC-103: Resize LUNs mapped to each server"
send_user "\n---------------------------------------------------------------------------------\n"
set testStep 0

array set diskList1 [getDisks $ovmServerMasterIP [array get myServerInfo]]
array set diskList2 [getDisks $ovmServerSlaveIP [array get myServerInfo]]
set sizelist {7 12}

# verify 
send_user "\n## [incr testStep 1]. Verifying the LUN resize on $masterName\n"
set length [array size diskList1]
set rcount 0
for {set i 0} {$i < $length} {incr i 1} {
    if {[refreshAndVerifySize $diskList1($i) $sizelist] == "True"} {
	incr rcount 1
    }
} 

if {$rcount != 1} {
    send_user "Expected one resized LUN on $masterName, but found $rcount!\nTerminating.\n"
    finishRun 2
}

send_user "\n## [incr testStep 1]. Verifying the LUN resize on $secondaryName\n"
set length [array size diskList2]
set rcount 0
for {set i 0} {$i < $length} {incr i 1} {
    if {[refreshAndVerifySize $diskList2($i) $sizelist] == "True"} {
	incr rcount 1
    }
} 

if {$rcount != 1} {
    send_user "Expected one resized LUN on $secondaryName, but found $rcount!\nTerminating.\n"
    finishRun 2
}

send_user "\n\nThe LUNs have been correctly resized!\n"
finishRun 0
