#!/usr/bin/expect

##
##    The Oracle Storage HCL Testkit is a suite of tests for certifying
##    storage with Oracle VM (OVM).
##    Copyright (C) 2013 Oracle USA, Inc 
##
##    This file is part of the Oracle Storage HCL Testkit.
##
##    The Oracle Storage HCL Testkit is free software; you can redistribute 
##    it and/or modify it under the terms of the GNU General Public License 
##    as published by the Free Software Foundation; either version 2 of the 
##    License, or (at your option) any later version.
##
##    The Oracle Storage HCL Testkit is distributed in the hope that it will
##    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
##    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with the Oracle Storage HCL Testkit.  If not; write to the 
##    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
##    Boston, MA 02110-1301 USA. Or see <http://www.gnu.org/licenses/>.
##

source commonExpectDef.cli

################ global variables #####################
set prompt "OVM> "
set VERBOSE [lindex $argv 3]
set send_human {.1 .3 1 .05 2}

set successMsg "Status: Success"
set failureMsg "Status: Failure"
set timeout 900

set myRepo ""
set myPoolFS ""
set repoDiskName ""
set poolfsDiskName ""
set sharedSpare ""
set spareDiskName ""

########## externally defined variables ############
set ovmUser ${ovmUser}
set adminServer ${adminServer}
set ovmPassword [lindex $argv 0]
set ovmAgentUsername ${ovmAgentUsername}
set ovmAgentPassword [lindex $argv 1]
set ovmServerMasterIP ${ovmServerMasterIP}
set ovmServerSlaveIP ${ovmServerSlaveIP}
set CHAP_UserName ${CHAP_UserName}
set CHAP_Password [lindex $argv 2]

## Pool Parameters
set serverPoolName iscsi_testpool1
set serverPoolIP ${serverPoolIP}

## Repository Parameters
set repoName repo_iscsi1.1
set vdiskName1 vdisk_iscsi1.1
set vdiskName2 vdisk_iscsi1.2

## VM Parameters
set vmName1 VM_iscsi1.1
set vmName2 VM_iscsi1.2

## Network
set VM_Network ${VM_Network}
set VM_Netmask ${VM_Netmask}
set VM_NetworkPort ${VM_NetworkPort}
set ovmServerMaster_vmnetworkIP ${ovmServerMaster_vmnetworkIP} 
set ovmServerSlave_vmnetworkIP ${ovmServerSlave_vmnetworkIP} 

                                                        
## Storage
set defaultSAN_Server "Unmanaged iSCSI Storage Array"
set SAN_ServerName ${SAN_ServerName}
set SAN_AccessHost ${SAN_AccessHost}
set SAN_AccessPort ${SAN_AccessPort}

set storageNetworkIP ${storageNetworkIP}
set storageNetworkPort ${storageNetworkPort}
set storageNetworkNetmask ${storageNetworkNetmask}
set ovmServerMaster_storageIP ${ovmServerMaster_storageIP}
set ovmServerSlave_storageIP ${ovmServerSlave_storageIP}

## Cleanup
set serverPoolList {iscsi_testpool1 fc_testpool1 nfs_testpool2.1 nfs_testpool2.2 iscsi_testpool3 fc_testpool3}
set repoList {repo_fc1.1 repo_iscsi1.1 repo_nfs2.1 repo_nfs2.2 repo_nfs2.3 repo_fc3.1 repo_iscsi3.1}
set vmList {VM_fc1.1 VM_fc1.2 VM_iscsi1.1 VM_iscsi1.2 VM_fc3.1 VM_fc3.2 VM_iscsi3.1 VM_iscsi3.2 VM_nfs2.1 VM_nfs2.2}


## Logging
set hcllogdir ${hcllogdir}
set logfile $hcllogdir
append logfile "iSCSI_TestSuite1-CHAP_Setup.log"
set testStep 0

#################################################################
##
##       Test Suite 1: iSCSI with Generic Plugin with CHAP
##
#################################################################

log_user 0
OVMlogin
log_file -a $logfile

send_user "\n----------------------------------------------------------------------------------\n"
send_user "GSIS-101: Discover OVM Servers "
send_user "\n----------------------------------------------------------------------------------\n"

send_user "\n## [incr testStep 1].  Discovering the Master Server\n"
send "discoverServer ipAddress=$ovmServerMasterIP port=8899 username=$ovmAgentUsername password=$ovmAgentPassword takeOwnership=yes\r"
validateCommandOutput "discoverServer command"

send_user "\n## [incr testStep 1].  Discovering the Secondary Server\n"
send "discoverServer ipAddress=$ovmServerSlaveIP port=8899 username=$ovmAgentUsername password=$ovmAgentPassword takeOwnership=yes\r"
validateCommandOutput "discoverServer command"

send_user "\nReading server info...\n"
set slist [getServerIDs]
array set myServerInfo [verifyServers $ovmServerMasterIP $ovmServerSlaveIP $storageNetworkPort $VM_NetworkPort $slist]

if {[info exists myServerInfo($ovmServerMasterIP,name)]} {
    set masterName $myServerInfo($ovmServerMasterIP,name)
} else {
    send_user "The server $ovmServerMasterIP cannot be found!\n"
    send_user "Exiting...\n"
    finishRun 4
}
if {[info exists myServerInfo($ovmServerSlaveIP,name)]} {
    set secondaryName $myServerInfo($ovmServerSlaveIP,name)
} else {
    send_user "The server $ovmServerSlaveIP cannot be found!\n"
    send_user "Exiting...\n"
    finishRun 4
}

set masterID $myServerInfo($ovmServerMasterIP,id)
set secondaryID $myServerInfo($ovmServerSlaveIP,id)

set masterPort $myServerInfo($ovmServerMasterIP,port)
set secondaryPort $myServerInfo($ovmServerSlaveIP,port)

set SCSI_Plugin [find_SCSI_Plugins "False" "SCSI"]
send_user "\n\nUsing the '$SCSI_Plugin' plugin, and attempting to\ncreate the storage network on $storageNetworkIP...\n"
createNetwork $storageNetworkIP STORAGE

array set NetworkInfo {}
set NetworkInfo(master,name) $masterName
set NetworkInfo(master,id) $masterPort
set NetworkInfo(master,ip) $ovmServerMaster_storageIP
set NetworkInfo(slave,name) $secondaryName
set NetworkInfo(slave,id) $secondaryPort
set NetworkInfo(slave,ip) $ovmServerSlave_storageIP

send_user "\nAttempting to add ports to the Storage Network...\n"
addPorts $storageNetworkNetmask $storageNetworkIP [array get NetworkInfo]

send_user "\n## [incr testStep 1]. Discovering the SAN Server: $SAN_ServerName\n"
send "create sanserver name=$SAN_ServerName plugin='$SCSI_Plugin' storageType=iSCSIStorageArray accessHost=$SAN_AccessHost accessPort=$SAN_AccessPort accessUsername=$CHAP_UserName accessPassword=$CHAP_Password useChap=yes\r"
validateCommandOutput "createSanServer command"

send_user "\nAdding $masterName and $secondaryName as admin servers for $SAN_ServerName.\n"
send_user "\n## [incr testStep 1].   Adding $masterName as admin server for $SAN_ServerName\n"
send "add server id=$masterID to SanServer name='$SAN_ServerName'\r"
validateCommandOutput "add server command"

send_user "\n## [incr testStep 1]. Adding $secondaryName as admin server for $SAN_ServerName\n"
send "add server id=$secondaryID to SanServer name='$SAN_ServerName'\r"
validateCommandOutput "add server command"

sleep 3
send_user "\n## [incr testStep 1]. Adding iSCSI initiators to the Default Access Group...\n"

set myAccessGroup [findAccessGroups]
addInitiators iscsi $masterName $myAccessGroup
sleep 3
addInitiators iscsi $secondaryName $myAccessGroup

send_user "\nWaiting one minute for everything to settle...\n"
sleep 60

## verify initial config -- no luns mapped to the servers
array set myNewServerInfo [verifyInitialConfig $ovmServerMasterIP $ovmServerSlaveIP [array get myServerInfo]]
set masterlocals $myNewServerInfo($ovmServerMasterIP,haslocal)
set secondlocals $myNewServerInfo($ovmServerSlaveIP,haslocal)

set masterTotal $masterlocals
set secondTotal $secondlocals


if {$myNewServerInfo($ovmServerMasterIP,verified) == "False" || $myNewServerInfo($ovmServerSlaveIP,verified) == "False"} {
    send_user "\n\nUnexpected initial state: Found LUNs mapped to servers!\n"
    send_user "Please unmap all LUNs and reboot the OVS servers.  After\n"
    send_user "the servers come back up, run the cleanup scripts by setting\n"
    send_user "the -k option.  Once the cleanup run has completed successfully,\n"
    send_user "start the test suite again.\n"
    finishRun 2
}

finishRun 0

